# Generated by Django 5.1.15 on 2026-01-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('proprietor_name', models.CharField(max_length=100)),
                ('phone_primary', models.CharField(max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('established_year', models.PositiveIntegerField(default=1995)),
            ],
        ),
    ]
